<?php
namespace AppBundle\Repository;
/**
 * ZamowienieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Pozycja_zamowieniaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllForCook()
    {
        return $this->createQueryBuilder('p')
                ->select('p, z')
                ->leftJoin('p.zamowienie', 'z')
                ->orderBy('z.czas_zlozenia', 'ASC')
                ->getQuery()
                ->getResult();
        
    }
}

