<?php
namespace AppBundle\Repository;
/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusZamowieniaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByName($name)
    {
        return $this->createQueryBuilder('s')
                ->where('nazwa = :nazwa')
                ->setParameter('nazwa', $name)
                ->getQuery()
                ->getOneOrNullResult();
    }
}

