# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_provider:
            entity:
                class: AppBundle:User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                
            logout:
                path: /logout
                target: /
                
    role_hierarchy:
        ROLE_CLIENT: ROLE_USER
        ROLE_WAITER: ROLE_USER
        ROLE_COOK: ROLE_USER
        ROLE_MANAGER: ROLE_USER
        ROLE_ADMIN: [ROLE_CLIENT, ROLE_WAITER, ROLE_COOK, ROLE_MANAGER]
                
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/adminPanel, roles: ROLE_ADMIN }
        - { path: ^/danie, roles: ROLE_ADMIN }
        - { path: ^/pozycja_zamowienia, roles: ROLE_ADMIN }
        - { path: ^/pracownik, roles: ROLE_ADMIN }
        - { path: ^/produkt, roles: ROLE_ADMIN }
        - { path: ^/rodzaj, roles: ROLE_ADMIN }
        - { path: ^/skladnik, roles: ROLE_ADMIN }
        - { path: ^/stanmagazynowy, roles: ROLE_ADMIN }
        - { path: ^/status_zamowienia, roles: ROLE_ADMIN }
        - { path: ^/zamowienie, roles: ROLE_ADMIN }
        - { path: ^/dostawca, roles: ROLE_ADMIN }
        - { path: ^/group, roles: ROLE_ADMIN }
        - { path: ^/jednostka, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
